
spring:
  devtools:
    livereload:
      enabled: true
      
  freemarker:
    cache: false
    
  thymeleaf:
    cache: false
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moonlight?serverTimezone=Asia/Seoul
    username: root
    password: root

# jsp파일을 읽어들이기 위해 접두사로 경로를 설정해주고 접미사로 .jsp설정
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # 추후에 update로 바꿔야함. 안그러면 실행할때마다 테이블 계속 create됨.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      
  jackson:
    serialization:
      fail-on-empty-beans: false
### 스프링 설정 완료.      
      
server:
  port: 8000
  servlet:
    context-path: /purplesheep
    encoding:
      charset: UTF-8
      enabled: true
      force: true      

